<?php

return [
    [
        "user_id" => 1,
        "name" => "John Michael",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/JD.jpg",
        "performance" => "",
        "promotions" => [3],
        "specializations" => [22],
    ],
    [
        "user_id" => 2,
        "name" => "Gregory",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Dr-House.jpg",
        "performance" => "",
        "promotions" => [3],
        "specializations" => [15, 16, 17],
    ],
    [
        "user_id" => 3,
        "name" => "James",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/James-WIlson.jpg",
        "performance" => "",
        "promotions" => [2],
        "specializations" => [18],
    ],
    [
        "user_id" => 4,
        "name" => "Eric",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Eric-Foreman.jpeg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [15, 19],
    ],
    [
        "user_id" => 5,
        "name" => "Martha",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Masters.jpeg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [15, 13],
    ],
    [
        "user_id" => 6,
        "name" => "Robert",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Robert-Chase.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [13, 15, 20],
    ],
    [
        "user_id" => 7,
        "name" => "Allison",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Cameron.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [15, 19],
    ],
    [
        "user_id" => 8,
        "name" => "Tredici",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/13.jpeg",
        "performance" => "",
        "promotions" => [1],
        "specializations" => [15, 22],
    ],
    [
        "user_id" => 9,
        "name" => "Chris",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Taub.jpg",
        "performance" => "",
        "promotions" => [3],
        "specializations" => [15, 21],
    ],
    [
        "user_id" => 10,
        "name" => "Lawrence",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Kutner.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [2],
    ],
    [
        "user_id" => 11,
        "name" => "Elliot",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Elliot-Reid.jpeg",
        "performance" => "",
        "promotions" => [1],
        "specializations" => [4, 14],
    ],
    [
        "user_id" => 12,
        "name" => "Christopher Duncan",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Christopher-Duncan-Turk.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [13, 1],
    ],
    [
        "user_id" => 13,
        "name" => "Percival Ulysses",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Cox.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [14, 6],
    ],
    [
        "user_id" => 14,
        "name" => "Robert-Kelso",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Robert-Kelso.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [9, 16],
    ],
    [
        "user_id" => 15,
        "name" => "Todd",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Tood.jpg",
        "performance" => "",
        "promotions" => [2],
        "specializations" => [9, 12, 16],
    ],
    [
        "user_id" => 16,
        "name" => "Helmut",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Alzheimer.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [13],
    ],
    [
        "user_id" => 17,
        "name" => "Doug",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Doug.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [22],
    ],
    [
        "user_id" => 18,
        "name" => "King",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Shulz.jpg",
        "performance" => " i Diagnosi, Cura e Riabilitazione rese alla persona nell'esercizio delle professioni e arti sanitarie soggette a vigilanza.",
        "promotions" => [],
        "specializations" => [23],
    ],
    [
        "user_id" => 19,
        "name" => "Alberto",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Fumagalli.jpg",
        "performance" => "",
        "promotions" => [1],
        "specializations" => [10],
    ],
    [
        "user_id" => 20,
        "name" => "Cristina",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Cristina_Yang.jpg",
        "performance" => "",
        "promotions" => [2],
        "specializations" => [24],
    ],
    [
        "user_id" => 21,
        "name" => "Izzie",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Izzie_Stevens.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [18],
    ],
    [
        "user_id" => 22,
        "name" => "Shaun",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Shaun.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [13],
    ],
    [
        "user_id" => 23,
        "name" => "Luigi",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Zampa.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [14],
    ],
    [
        "user_id" => 24,
        "name" => "Peter",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Peter_Benton.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [13],
    ],
    [
        "user_id" => 25,
        "name" => "Giorgia",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Gio.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [9],
    ],

    [
        "user_id" => 26,
        "name" => "Mark",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Sloan.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [21],
    ],

    [
        "user_id" => 27,
        "name" => "Stephen",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Strange.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [25],
    ],

    [
        "user_id" => 28,
        "name" => "Hunter Patch",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Patch_Adams.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [4],
    ],

    [
        "user_id" => 29,
        "name" => "Douglas",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/dott_male.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [4],
    ],

    [
        "user_id" => 30,
        "name" => "John Dolittle",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Dolittle.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [13],
    ],

    [
        "user_id" => 31,
        "name" => "Octavius Gunther",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Ock.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [8],
    ],


    [
        "user_id" => 32,
        "name" => "Emmett",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Emmett.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [15],
    ],

    [
        "user_id" => 33,
        "name" => "Guido",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Guido.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [14],
    ],

    [
        "user_id" => 34,
        "name" => "Jack",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Jack_shep.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [25],
    ],

    [
        "user_id" => 35,
        "name" => "Meredith",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Meredith.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [13, 20],
    ],

    [
        "user_id" => 36,
        "name" => "Alex",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/karev.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [4],
    ],

    [
        "user_id" => 37,
        "name" => "Miranda",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Miranda.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [22, 20],
    ],

     [
        "user_id" => 38,
        "name" => "Callie",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Callie.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [2],
    ],

    [
        "user_id" => 39,
        "name" => "April",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/April.jpg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [3, 5],
    ],

    [
        "user_id" => 40,
        "name" => "Jo",
        "telephone" => "1234567890",
        "curriculum_vitae" => "",
        "image" => "Profile_IMG/Jo.jpeg",
        "performance" => "",
        "promotions" => [],
        "specializations" => [11, 12, 13],
    ],
];
