<?php

return [
    [
        'doctor_id' => 1,
        'valutation' => 5,
        'name' => 'Maria',
        'review' => 'Eccellente',
    ],
    [
        'doctor_id' => 1,
        'valutation' => '3',
        'name'  => 'Luca',
        'review' => 'Modesto',
    ],
    [
        'doctor_id' => 1,
        'valutation' => '1',
        'name'  => 'Pietro',
        'review' => 'Scarso',
    ],
    [
        'doctor_id' => 1,
        'valutation' => '5',
        'name'  => 'Enrico',
        'review' => 'Consigliato, ottimo professionista',
    ],
    [
        'doctor_id' => 1,
        'valutation' => '2',
        'name'  => 'Marcello',
        'review' => 'cercate altrove',
    ],
    [
        'doctor_id' => 2,
        'valutation' => 4,
        'name' => 'Giulia',
        'review' => 'Buon medico, lo consiglio!',
    ],
    [
        'doctor_id' => 2,
        'valutation' => 2,
        'name' => 'Lorenzo',
        'review' => 'Niente di speciale.',
    ],
    [
        'doctor_id' => 3,
        'valutation' => 5,
        'name' => 'Carla',
        'review' => 'Il migliore!',
    ],
    [
        'doctor_id' => 2,
        'valutation' => 4,
        'name' => 'Alice',
        'review' => 'Molto professionale, mi ha aiutato molto.',
    ],
    [
        'doctor_id' => 3,
        'valutation' => 5,
        'name' => 'Giovanni',
        'review' => 'Il miglior dottore che abbia mai incontrato.',
    ],
    [
        'doctor_id' => 4,
        'valutation' => 3,
        'name' => 'Laura',
        'review' => 'Niente di speciale.',
    ],
    [
        'doctor_id' => 5,
        'valutation' => 2,
        'name' => 'Marco',
        'review' => 'Non lo consiglierei a nessuno.',
    ],
    [
        'doctor_id' => 6,
        'valutation' => 4,
        'name' => 'Anna',
        'review' => 'Bravo medico, ma lunghe attese in studio.',
    ],
    [
        'doctor_id' => 1,
        'valutation' => 5,
        'name' => 'Maria',
        'review' => 'Eccellente',
    ],
    [
        'doctor_id' => 2,
        'valutation' => 4,
        'name' => 'Luca',
        'review' => 'Molto professionale, lo consiglio.',
    ],
    [
        'doctor_id' => 3,
        'valutation' => 3,
        'name' => 'Pietro',
        'review' => 'Niente di speciale.',
    ],
    [
        'doctor_id' => 4,
        'valutation' => 2,
        'name' => 'Anna',
        'review' => 'Lunghe attese in studio, non lo consiglio.',
    ],
    [
        'doctor_id' => 5,
        'valutation' => 5,
        'name' => 'Giovanni',
        'review' => 'Il miglior medico che abbia mai incontrato.',
    ],
    [
        'doctor_id' => 1,
        'valutation' => 5,
        'name' => 'Maria',
        'review' => 'Eccellente medico, altamente raccomandato.',
    ],
    [
        'doctor_id' => 2,
        'valutation' => 4,
        'name' => 'Luca',
        'review' => 'Ho ricevuto un buon trattamento dal dottore.',
    ],
    [
        'doctor_id' => 3,
        'valutation' => 3,
        'name' => 'Pietro',
        'review' => 'Niente di speciale, servizio standard.',
    ],
    [
        'doctor_id' => 11,
        'valutation' => 4,
        'name' => 'Marco',
        'review' => 'Un medico molto competente e gentile.',
    ],
    [
        'doctor_id' => 12,
        'valutation' => 3,
        'name' => 'Alessia',
        'review' => 'Niente di eccezionale, ma fa il suo lavoro.',
    ],
    [
        'doctor_id' => 13,
        'valutation' => 5,
        'name' => 'Giulia',
        'review' => 'Il mio medico di fiducia, sempre disponibile.',
    ],
    [
        'doctor_id' => 14,
        'valutation' => 2,
        'name' => 'Roberto',
        'review' => 'Non sono soddisfatto del servizio ricevuto.',
    ],
    [
        'doctor_id' => 15,
        'valutation' => 4,
        'name' => 'Sara',
        'review' => 'Mi ha aiutato a risolvere il mio problema di salute.',
    ],
    [
        'doctor_id' => 16,
        'valutation' => 5,
        'name' => 'Giovanna',
        'review' => 'Eccellente medico, sempre attento alle esigenze del paziente.',
    ],
    [
        'doctor_id' => 17,
        'valutation' => 3,
        'name' => 'Fabio',
        'review' => 'Servizio accettabile, ma migliorabile.',
    ],
    [
        'doctor_id' => 18,
        'valutation' => 4,
        'name' => 'Elisa',
        'review' => 'Consigliato a chiunque abbia bisogno di un buon medico.',
    ],
    [
        'doctor_id' => 19,
        'valutation' => 1,
        'name' => 'Luigi',
        'review' => 'Esperienza terribile, non tornerei mai.',
    ],
    [
        'doctor_id' => 20,
        'valutation' => 5,
        'name' => 'Paola',
        'review' => 'Il dottore migliore che abbia mai incontrato.',
    ],
    [
        'doctor_id' => 21,
        'valutation' => 4,
        'name' => 'Marta',
        'review' => 'Un medico molto competente e attento alle esigenze dei pazienti.',
    ],
    [
        'doctor_id' => 22,
        'valutation' => 3,
        'name' => 'Davide',
        'review' => 'Niente di eccezionale, ma soddisfacente.',
    ],
    [
        'doctor_id' => 23,
        'valutation' => 5,
        'name' => 'Silvia',
        'review' => 'Sempre disponibile e gentile, consigliato.',
    ],
    [
        'doctor_id' => 24,
        'valutation' => 2,
        'name' => 'Riccardo',
        'review' => 'Servizio deludente, non lo consiglio.',
    ],
    [
        'doctor_id' => 25,
        'valutation' => 4,
        'name' => 'Elena',
        'review' => 'Mi ha aiutato a migliorare la mia salute, grazie.',
    ],
    [
        'doctor_id' => 26,
        'valutation' => 5,
        'name' => 'Alessandra',
        'review' => 'Un vero professionista, sempre disponibile.',
    ],
    [
        'doctor_id' => 27,
        'valutation' => 3,
        'name' => 'Alberto',
        'review' => 'Accettabile, ma con margini di miglioramento.',
    ],
    [
        'doctor_id' => 28,
        'valutation' => 4,
        'name' => 'Giorgio',
        'review' => 'Consigliato a chiunque cerchi un buon medico.',
    ],
    [
        'doctor_id' => 29,
        'valutation' => 1,
        'name' => 'Cristina',
        'review' => 'Esperienza terribile, da evitare assolutamente.',
    ],
    [
        'doctor_id' => 30,
        'valutation' => 5,
        'name' => 'Carlo',
        'review' => 'Il miglior medico che abbia mai incontrato.',
    ],
    [
        'doctor_id' => 31,
        'valutation' => 4,
        'name' => 'Valeria',
        'review' => 'Un medico molto competente e gentile.',
    ],
    [
        'doctor_id' => 32,
        'valutation' => 3,
        'name' => 'Massimo',
        'review' => 'Buon servizio, ma con spazio per miglioramenti.',
    ],
    [
        'doctor_id' => 33,
        'valutation' => 5,
        'name' => 'Daniela',
        'review' => 'Sempre disponibile e professionale, consigliato.',
    ],
    [
        'doctor_id' => 34,
        'valutation' => 2,
        'name' => 'Lorenzo',
        'review' => 'Esperienza negativa, non lo consiglio.',
    ],
    [
        'doctor_id' => 35,
        'valutation' => 4,
        'name' => 'Francesca',
        'review' => 'Mi ha aiutato a risolvere i miei problemi di salute.',
    ],
    [
        'doctor_id' => 36,
        'valutation' => 5,
        'name' => 'Federica',
        'review' => 'Un medico eccellente, sempre attento.',
    ],
    [
        'doctor_id' => 37,
        'valutation' => 3,
        'name' => 'Andrea',
        'review' => 'Niente di speciale, ma fa il suo lavoro.',
    ],
    [
        'doctor_id' => 38,
        'valutation' => 4,
        'name' => 'Sergio',
        'review' => 'Buon medico, lo consiglio.',
    ],
    [
        'doctor_id' => 39,
        'valutation' => 1,
        'name' => 'Barbara',
        'review' => 'Esperienza pessima, da evitare.',
    ],
    [
        'doctor_id' => 40,
        'valutation' => 5,
        'name' => 'Roberta',
        'review' => 'Il miglior medico che abbia mai incontrato.',
    ],
    [
        'doctor_id' => 30,
        'valutation' => 4,
        'name' => 'Chiara',
        'review' => 'Mi ha fornito una buona cura, lo consiglio.',
    ],
    [
        'doctor_id' => 31,
        'valutation' => 3,
        'name' => 'Lorenzo',
        'review' => 'Servizio standard, niente di eccezionale.',
    ],
    [
        'doctor_id' => 32,
        'valutation' => 5,
        'name' => 'Roberta',
        'review' => 'Il medico migliore in circolazione!',
    ],
    [
        'doctor_id' => 33,
        'valutation' => 2,
        'name' => 'Davide',
        'review' => 'Non ho avuto una buona esperienza.',
    ],
    [
        'doctor_id' => 34,
        'valutation' => 4,
        'name' => 'Alessandra',
        'review' => 'Mi ha aiutato a risolvere il mio problema di salute.',
    ],
    [
        'doctor_id' => 35,
        'valutation' => 5,
        'name' => 'Giovanni',
        'review' => 'Altamente professionale e gentile.',
    ],
    [
        'doctor_id' => 36,
        'valutation' => 3,
        'name' => 'Marta',
        'review' => 'Servizio accettabile, ma migliorabile.',
    ],
    [
        'doctor_id' => 37,
        'valutation' => 4,
        'name' => 'Paolo',
        'review' => 'Consigliato per le sue competenze mediche.',
    ],
    [
        'doctor_id' => 38,
        'valutation' => 1,
        'name' => 'Sara',
        'review' => 'Esperienza pessima, non tornerei mai.',
    ],
    [
        'doctor_id' => 39,
        'valutation' => 5,
        'name' => 'Lorenza',
        'review' => 'Il migliore tra tutti i medici che ho visto.',
    ],
    [
        'doctor_id' => 40,
        'valutation' => 4,
        'name' => 'Antonio',
        'review' => 'Un professionista competente e disponibile.',
    ],
    [
        'doctor_id' => 21,
        'valutation' => 4,
        'name' => 'Simone',
        'review' => 'Professionale e competente, ottimo medico.',
    ],
    [
        'doctor_id' => 22,
        'valutation' => 3,
        'name' => 'Laura',
        'review' => 'Servizio accettabile, ma nulla di eccezionale.',
    ],
    [
        'doctor_id' => 23,
        'valutation' => 5,
        'name' => 'Giovanni',
        'review' => 'Il miglior medico che abbia mai incontrato.',
    ],
    [
        'doctor_id' => 24,
        'valutation' => 2,
        'name' => 'Elena',
        'review' => 'Esperienza deludente, non lo consiglio.',
    ],
    [
        'doctor_id' => 25,
        'valutation' => 4,
        'name' => 'Roberto',
        'review' => 'Mi ha aiutato a risolvere il mio problema di salute.',
    ],
    [
        'doctor_id' => 26,
        'valutation' => 5,
        'name' => 'Marta',
        'review' => 'Un medico eccellente, sempre attento alle esigenze dei pazienti.',
    ],
    [
        'doctor_id' => 27,
        'valutation' => 3,
        'name' => 'Alessio',
        'review' => 'Servizio standard, nulla di speciale.',
    ],
    [
        'doctor_id' => 28,
        'valutation' => 4,
        'name' => 'Sara',
        'review' => 'Consigliato per la sua competenza medica.',
    ],
    [
        'doctor_id' => 29,
        'valutation' => 1,
        'name' => 'Davide',
        'review' => 'Esperienza orribile, da evitare.',
    ],
    [
        'doctor_id' => 30,
        'valutation' => 5,
        'name' => 'Alice',
        'review' => 'Il migliore tra tutti i medici che ho visto.',
    ],
    [
        'doctor_id' => 31,
        'valutation' => 4,
        'name' => 'Antonia',
        'review' => 'Professionale e disponibile, ottimo servizio.',
    ],
    [
        'doctor_id' => 32,
        'valutation' => 3,
        'name' => 'Luca',
        'review' => 'Buon medico, ma migliorabile.',
    ],
    [
        'doctor_id' => 33,
        'valutation' => 5,
        'name' => 'Giulia',
        'review' => 'Sempre disponibile e gentile, altamente raccomandata.',
    ],
    [
        'doctor_id' => 34,
        'valutation' => 2,
        'name' => 'Lorenzo',
        'review' => 'Esperienza negativa, non tornerei mai.',
    ],
    [
        'doctor_id' => 35,
        'valutation' => 4,
        'name' => 'Federica',
        'review' => 'Mi ha aiutato a risolvere i miei problemi di salute, ottimo medico.',
    ],
    [
        'doctor_id' => 36,
        'valutation' => 5,
        'name' => 'Massimo',
        'review' => 'Un medico straordinario, sempre pronto ad aiutare.',
    ],
    [
        'doctor_id' => 37,
        'valutation' => 3,
        'name' => 'Martina',
        'review' => 'Niente di speciale, ma fa il suo lavoro.',
    ],
    [
        'doctor_id' => 38,
        'valutation' => 4,
        'name' => 'Sergio',
        'review' => 'Consigliato per le sue competenze mediche.',
    ],
    [
        'doctor_id' => 39,
        'valutation' => 1,
        'name' => 'Elisa',
        'review' => 'Esperienza terribile, da evitare.',
    ],
    [
        'doctor_id' => 40,
        'valutation' => 5,
        'name' => 'Roberto',
        'review' => 'Il miglior medico che abbia mai incontrato.',
    ],
    [
        'doctor_id' => 10,
        'valutation' => 4,
        'name' => 'Alessio',
        'review' => 'Un medico molto competente e gentile.',
    ],
    [
        'doctor_id' => 11,
        'valutation' => 3,
        'name' => 'Giada',
        'review' => 'Servizio accettabile, ma migliorabile.',
    ],
    [
        'doctor_id' => 12,
        'valutation' => 5,
        'name' => 'Matteo',
        'review' => 'Il miglior medico che abbia mai incontrato.',
    ],
    [
        'doctor_id' => 13,
        'valutation' => 2,
        'name' => 'Valentina',
        'review' => 'Esperienza deludente, non lo consiglio.',
    ],
    [
        'doctor_id' => 14,
        'valutation' => 4,
        'name' => 'Lorenzo',
        'review' => 'Mi ha aiutato a risolvere il mio problema di salute.',
    ],
    [
        'doctor_id' => 15,
        'valutation' => 5,
        'name' => 'Aurora',
        'review' => 'Un medico eccellente, sempre attento alle esigenze dei pazienti.',
    ],
    [
        'doctor_id' => 16,
        'valutation' => 3,
        'name' => 'Gabriele',
        'review' => 'Servizio standard, niente di speciale.',
    ],
    [
        'doctor_id' => 17,
        'valutation' => 4,
        'name' => 'Elisa',
        'review' => 'Consigliato per la sua competenza medica.',
    ],
    [
        'doctor_id' => 18,
        'valutation' => 1,
        'name' => 'Daniele',
        'review' => 'Esperienza orribile, da evitare.',
    ],
    [
        'doctor_id' => 19,
        'valutation' => 5,
        'name' => 'Sara',
        'review' => 'Il migliore tra tutti i medici che ho visto.',
    ],
    [
        'doctor_id' => 20,
        'valutation' => 4,
        'name' => 'Fabio',
        'review' => 'Professionale e disponibile, ottimo medico.',
    ],
    [
        'doctor_id' => 21,
        'valutation' => 3,
        'name' => 'Francesca',
        'review' => 'Buon medico, ma migliorabile.',
    ],
    [
        'doctor_id' => 22,
        'valutation' => 5,
        'name' => 'Marco',
        'review' => 'Sempre disponibile e gentile, altamente raccomandato.',
    ],
    [
        'doctor_id' => 23,
        'valutation' => 2,
        'name' => 'Marta',
        'review' => 'Esperienza negativa, non tornerei mai.',
    ],
    [
        'doctor_id' => 24,
        'valutation' => 4,
        'name' => 'Nicola',
        'review' => 'Mi ha aiutato a risolvere i miei problemi di salute, ottimo medico.',
    ],
    [
        'doctor_id' => 25,
        'valutation' => 5,
        'name' => 'Sonia',
        'review' => 'Un medico straordinario, sempre pronto ad aiutare.',
    ],
    [
        'doctor_id' => 26,
        'valutation' => 3,
        'name' => 'Gianluca',
        'review' => 'Niente di speciale, ma fa il suo lavoro.',
    ],
    [
        'doctor_id' => 27,
        'valutation' => 4,
        'name' => 'Elisabetta',
        'review' => 'Consigliato per la sua competenza medica.',
    ],
    [
        'doctor_id' => 28,
        'valutation' => 1,
        'name' => 'Stefano',
        'review' => 'Esperienza pessima, da evitare.',
    ],
    [
        'doctor_id' => 29,
        'valutation' => 5,
        'name' => 'Silvia',
        'review' => 'Il miglior medico che abbia mai incontrato.',
    ],
    [
        'doctor_id' => 30,
        'valutation' => 4,
        'name' => 'Andrea',
        'review' => 'Professionale e competente, ottimo servizio.',
    ],
    [
        'doctor_id' => 31,
        'valutation' => 3,
        'name' => 'Alessandra',
        'review' => 'Buon medico, ma migliorabile.',
    ],
    [
        'doctor_id' => 32,
        'valutation' => 5,
        'name' => 'Luigi',
        'review' => 'Sempre disponibile e gentile, altamente raccomandato.',
    ],
    [
        'doctor_id' => 33,
        'valutation' => 2,
        'name' => 'Maria',
        'review' => 'Esperienza negativa, non tornerei mai.',
    ],
    [
        'doctor_id' => 34,
        'valutation' => 4,
        'name' => 'Claudia',
        'review' => 'Mi ha aiutato a risolvere il mio problema di salute, ottimo medico.',
    ],
    [
        'doctor_id' => 35,
        'valutation' => 5,
        'name' => 'Emanuele',
        'review' => 'Un medico straordinario, sempre pronto ad aiutare.',
    ],
    [
        'doctor_id' => 36,
        'valutation' => 3,
        'name' => 'Laura',
        'review' => 'Niente di speciale, ma fa il suo lavoro.',
    ],
    [
        'doctor_id' => 37,
        'valutation' => 4,
        'name' => 'Federico',
        'review' => 'Consigliato per la sua competenza medica.',
    ],
    [
        'doctor_id' => 38,
        'valutation' => 1,
        'name' => 'Giorgio',
        'review' => 'Esperienza pessima, da evitare.',
    ],
    [
        'doctor_id' => 39,
        'valutation' => 5,
        'name' => 'Cristina',
        'review' => 'Il miglior medico che abbia mai incontrato.',
    ],
    [
        'doctor_id' => 40,
        'valutation' => 4,
        'name' => 'Stefania',
        'review' => 'Professionale e disponibile, ottimo medico.',
    ],
];
